// SINGLE SOURCE OF TRUTH - Platforms definition
const PLATFORMS = [
    { name: "atari", vendor: "Atari", displayName: "2600", extensions: [".zip"] },
    { name: "spectrum", vendor: "Sinclair", displayName: "ZX Spectrum", extensions: [".zip"] },
    { name: "c64", vendor: "Commodore", displayName: "64", extensions: [".zip"] },
    { name: "nes", vendor: "Nintendo", displayName: "NES", extensions: [".zip"] },
    { name: "sms", vendor: "Sega", displayName: "Master System", extensions: [".zip"] },
    { name: "pcengine", vendor: "NEC", displayName: "PC Engine", extensions: [".pce"] },
    { name: "amiga", vendor: "Commodore", displayName: "Amiga", extensions: [".lha", ".adf"] },
    { name: "megadrive", vendor: "Sega", displayName: "Mega Drive", extensions: [".md"] },
    { name: "gameboy", vendor: "Nintendo", displayName: "Game Boy", extensions: [".md"] },
    { name: "lynx", vendor: "Atari", displayName: "Lynx", extensions: [".md"] },
    { name: "gamegear", vendor: "Sega", displayName: "Game Gear", extensions: [".zip"] },
    { name: "snes", vendor: "Nintendo", displayName: "SNES", extensions: [".smc"] },
    { name: "jaguar", vendor: "Atari", displayName: "Jaguar", extensions: [".jag"] },
    { name: "saturn", vendor: "Sega", displayName: "Saturn", extensions: [".cue"] },
    { name: "psx", vendor: "Sony", displayName: "PlayStation", extensions: [".cue"] },
    { name: "n64", vendor: "Nintendo", displayName: "Nintendo 64", extensions: [".z64"] },
    { name: "dreamcast", vendor: "Sega", displayName: "Dreamcast", extensions: [".gdi", ".cdi"] },
    { name: "ps2", vendor: "Sony", displayName: "PlayStation 2", extensions: [".bin", ".iso"] },
    { name: "gamecube", vendor: "Nintendo", displayName: "GameCube", extensions: [".iso", ".ciso"] },
    { name: "xbox", vendor: "Microsoft", displayName: "Xbox", extensions: [".iso"] },
    { name: "psp", vendor: "Sony", displayName: "PSP", extensions: [".iso"] },
    { name: "ps3", vendor: "Sony", displayName: "PlayStation 3", extensions: [".SFO"] },
    { name: "3ds", vendor: "Nintendo", displayName: "3DS", extensions: [".3ds"] },
    { name: "xbox360", vendor: "Microsoft", displayName: "Xbox 360", extensions: [".iso", ".xex"] },
    { name: "ps4", vendor: "Sony", displayName: "PlayStation 4", extensions: [".iso"] }
];
